apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: version-forget-me-not
  title: Version Forget-Me-Not
  description: Github action for checking the version is updated in pull request
spec:
  type: github action
  lifecycle: production
