site_name: version-forget-me-not docs
repo_url: https://github.com/simplybusiness/version-forget-me-not
edit_uri: blob/master/docs/
docs_dir: "docs"
nav:
  - Home: index.md
plugins:
  - techdocs-core
