name: Ruby CI

on:
  push:
    branches:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run test
        run: bundle exec rspec spec
