name: Ruby CI

on:
  push:
    branches:

env:
  CI: true

jobs:
  build:
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1", "3.2"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run test
        run: bundle exec rspec spec
